import React, {useEffect} from "react";
import {useParams} from "react-router-dom";
import {IGame} from "../interfaces/game";
import GameTeamStats from "../components/gameTeamStats/gameTeamStats";
import GameTeamPlayerStats from "../components/gameTeamPlayerStats/gameTeamPlayerStats";
import {IGameTeamStats, IPlayerStats} from "../interfaces/stats";
import {getIndividualGameByGameId} from "../services/gameData";
import {
  getGameStatsData,
  getPlayerStatsPerGameData,
} from "../services/statsData";
import LiveGameCard from "../components/gameCards/liveGameCard";
import {IGameComment} from "../interfaces/gameComment";
import {getGameCommentsByGame} from "../services/GameCommentService";
import Comment from "../components/comment/comment";
import GameComments from "../components/gameComments/gameComments";
const temp2: IPlayerStats[] = [
  {
    firstName: "Kevin",
    lastName: "Durant",
    teamId: 4,
    playerId: 153,
    points: 32,
    fgm: 13,
    fga: 25,
    fgp: "52.0",
    ftm: 3,
    fta: 6,
    ftp: "50.0",
    tpm: 3,
    tpa: 7,
    tpp: "42.9",
    offensiveRebounds: 0,
    defensiveRebounds: 11,
    totalRebounds: 11,
    assists: 4,
    steals: 0,
    blocks: 2,
    fouls: 2,
    plusMinus: "-20",
    turnovers: 1,
  },
  {
    firstName: "Blake",
    lastName: "Griffin",
    teamId: 4,
    playerId: 208,
    points: 6,
    fgm: 2,
    fga: 5,
    fgp: "40.0",
    ftm: 2,
    fta: 2,
    ftp: "100",
    tpm: 0,
    tpa: 1,
    tpp: "0.0",
    offensiveRebounds: 1,
    defensiveRebounds: 4,
    totalRebounds: 5,
    assists: 0,
    steals: 1,
    blocks: 0,
    fouls: 1,
    plusMinus: "-6",
    turnovers: 1,
  },
  {
    firstName: "Nic",
    lastName: "Claxton",
    teamId: 4,
    playerId: 1854,
    points: 12,
    fgm: 6,
    fga: 9,
    fgp: "66.7",
    ftm: 0,
    fta: 3,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 7,
    totalRebounds: 7,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 3,
    plusMinus: "-15",
    turnovers: 0,
  },
  {
    firstName: "Joe",
    lastName: "Harris",
    teamId: 4,
    playerId: 221,
    points: 9,
    fgm: 3,
    fga: 9,
    fgp: "33.3",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 3,
    tpa: 5,
    tpp: "60.0",
    offensiveRebounds: 0,
    defensiveRebounds: 2,
    totalRebounds: 2,
    assists: 2,
    steals: 0,
    blocks: 0,
    fouls: 1,
    plusMinus: "0",
    turnovers: 2,
  },
  {
    firstName: "James",
    lastName: "Harden",
    teamId: 4,
    playerId: 216,
    points: 20,
    fgm: 6,
    fga: 16,
    fgp: "37.5",
    ftm: 4,
    fta: 4,
    ftp: "100",
    tpm: 4,
    tpa: 8,
    tpp: "50.0",
    offensiveRebounds: 3,
    defensiveRebounds: 5,
    totalRebounds: 8,
    assists: 8,
    steals: 1,
    blocks: 2,
    fouls: 3,
    plusMinus: "-20",
    turnovers: 4,
  },
  {
    firstName: "LaMarcus",
    lastName: "Aldridge",
    teamId: 4,
    playerId: 8,
    points: 1,
    fgm: 0,
    fga: 2,
    fgp: "0.0",
    ftm: 1,
    fta: 4,
    ftp: "25.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 3,
    totalRebounds: 3,
    assists: 1,
    steals: 0,
    blocks: 1,
    fouls: 2,
    plusMinus: "2",
    turnovers: 1,
  },
  {
    firstName: "DeAndre'",
    lastName: "Bembry",
    teamId: 4,
    playerId: 49,
    points: 0,
    fgm: 0,
    fga: 0,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    totalRebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "-9",
    turnovers: 0,
  },
  {
    firstName: "Bruce",
    lastName: "Brown",
    teamId: 4,
    playerId: 944,
    points: 0,
    fgm: 0,
    fga: 0,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 1,
    totalRebounds: 1,
    assists: 0,
    steals: 0,
    blocks: 1,
    fouls: 0,
    plusMinus: "-9",
    turnovers: 0,
  },
  {
    firstName: "Jevon",
    lastName: "Carter",
    teamId: 4,
    playerId: 949,
    points: 0,
    fgm: 0,
    fga: 3,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 2,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 2,
    totalRebounds: 2,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 1,
    plusMinus: "-29",
    turnovers: 1,
  },
  {
    firstName: "David",
    lastName: "Duke Jr.",
    teamId: 4,
    playerId: 2804,
    points: 0,
    fgm: 0,
    fga: 0,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    totalRebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "0",
    turnovers: 0,
  },
  {
    firstName: "Kessler",
    lastName: "Edwards",
    teamId: 4,
    playerId: 2805,
    points: 0,
    fgm: 0,
    fga: 0,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    totalRebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "0",
    turnovers: 0,
  },
  {
    firstName: "James",
    lastName: "Johnson",
    teamId: 4,
    playerId: 274,
    points: 1,
    fgm: 0,
    fga: 2,
    fgp: "0.0",
    ftm: 1,
    fta: 2,
    ftp: "50.0",
    tpm: 0,
    tpa: 1,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    totalRebounds: 0,
    assists: 2,
    steals: 0,
    blocks: 1,
    fouls: 3,
    plusMinus: "-6",
    turnovers: 0,
  },
  {
    firstName: "Patty",
    lastName: "Mills",
    teamId: 4,
    playerId: 365,
    points: 21,
    fgm: 7,
    fga: 11,
    fgp: "63.6",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 7,
    tpa: 7,
    tpp: "100",
    offensiveRebounds: 0,
    defensiveRebounds: 2,
    totalRebounds: 2,
    assists: 2,
    steals: 1,
    blocks: 1,
    fouls: 1,
    plusMinus: "7",
    turnovers: 0,
  },
  {
    firstName: "Paul",
    lastName: "Millsap",
    teamId: 4,
    playerId: 366,
    points: 0,
    fgm: 0,
    fga: 0,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 1,
    defensiveRebounds: 2,
    totalRebounds: 3,
    assists: 0,
    steals: 0,
    blocks: 1,
    fouls: 0,
    plusMinus: "-1",
    turnovers: 1,
  },
  {
    firstName: "Cam",
    lastName: "Thomas",
    teamId: 4,
    playerId: 2855,
    points: 2,
    fgm: 0,
    fga: 2,
    fgp: "0.0",
    ftm: 2,
    fta: 2,
    ftp: "100",
    tpm: 0,
    tpa: 1,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    totalRebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "-9",
    turnovers: 1,
  },
  {
    firstName: "Khris",
    lastName: "Middleton",
    teamId: 21,
    playerId: 361,
    points: 20,
    fgm: 8,
    fga: 17,
    fgp: "47.1",
    ftm: 3,
    fta: 4,
    ftp: "75.0",
    tpm: 1,
    tpa: 4,
    tpp: "25.0",
    offensiveRebounds: 0,
    defensiveRebounds: 9,
    totalRebounds: 9,
    assists: 3,
    steals: 1,
    blocks: 0,
    fouls: 3,
    plusMinus: "20",
    turnovers: 1,
  },
  {
    firstName: "Giannis",
    lastName: "Antetokounmpo",
    teamId: 21,
    playerId: 20,
    points: 32,
    fgm: 12,
    fga: 25,
    fgp: "48.0",
    ftm: 7,
    fta: 9,
    ftp: "77.8",
    tpm: 1,
    tpa: 4,
    tpp: "25.0",
    offensiveRebounds: 5,
    defensiveRebounds: 9,
    totalRebounds: 14,
    assists: 7,
    steals: 1,
    blocks: 2,
    fouls: 4,
    plusMinus: "25",
    turnovers: 4,
  },
  {
    firstName: "Brook",
    lastName: "Lopez",
    teamId: 21,
    playerId: 323,
    points: 8,
    fgm: 3,
    fga: 9,
    fgp: "33.3",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 2,
    tpa: 4,
    tpp: "50.0",
    offensiveRebounds: 2,
    defensiveRebounds: 3,
    totalRebounds: 5,
    assists: 0,
    steals: 1,
    blocks: 3,
    fouls: 3,
    plusMinus: "0",
    turnovers: 0,
  },
  {
    firstName: "Grayson",
    lastName: "Allen",
    teamId: 21,
    playerId: 926,
    points: 10,
    fgm: 3,
    fga: 10,
    fgp: "30.0",
    ftm: 1,
    fta: 1,
    ftp: "100",
    tpm: 3,
    tpa: 10,
    tpp: "30.0",
    offensiveRebounds: 0,
    defensiveRebounds: 4,
    totalRebounds: 4,
    assists: 6,
    steals: 2,
    blocks: 0,
    fouls: 0,
    plusMinus: "23",
    turnovers: 0,
  },
  {
    firstName: "Jrue",
    lastName: "Holiday",
    teamId: 21,
    playerId: 242,
    points: 12,
    fgm: 5,
    fga: 7,
    fgp: "71.4",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 2,
    tpa: 4,
    tpp: "50.0",
    offensiveRebounds: 1,
    defensiveRebounds: 0,
    totalRebounds: 1,
    assists: 1,
    steals: 1,
    blocks: 0,
    fouls: 0,
    plusMinus: "17",
    turnovers: 0,
  },
  {
    firstName: "Thanasis",
    lastName: "Antetokounmpo",
    teamId: 21,
    playerId: 2408,
    points: 6,
    fgm: 2,
    fga: 3,
    fgp: "66.7",
    ftm: 2,
    fta: 2,
    ftp: "100",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 1,
    defensiveRebounds: 3,
    totalRebounds: 4,
    assists: 1,
    steals: 0,
    blocks: 1,
    fouls: 1,
    plusMinus: "8",
    turnovers: 0,
  },
  {
    firstName: "Pat",
    lastName: "Connaughton",
    teamId: 21,
    playerId: 115,
    points: 20,
    fgm: 8,
    fga: 13,
    fgp: "61.5",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 4,
    tpa: 9,
    tpp: "44.4",
    offensiveRebounds: 0,
    defensiveRebounds: 3,
    totalRebounds: 3,
    assists: 2,
    steals: 1,
    blocks: 1,
    fouls: 0,
    plusMinus: "0",
    turnovers: 0,
  },
  {
    firstName: "George",
    lastName: "Hill",
    teamId: 21,
    playerId: 237,
    points: 1,
    fgm: 0,
    fga: 3,
    fgp: "0.0",
    ftm: 1,
    fta: 2,
    ftp: "50.0",
    tpm: 0,
    tpa: 2,
    tpp: "0.0",
    offensiveRebounds: 2,
    defensiveRebounds: 3,
    totalRebounds: 5,
    assists: 3,
    steals: 0,
    blocks: 1,
    fouls: 5,
    plusMinus: "-6",
    turnovers: 1,
  },
  {
    firstName: "Georgios",
    lastName: "Kalaitzakis",
    teamId: 21,
    playerId: 2824,
    points: 0,
    fgm: 0,
    fga: 2,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 2,
    defensiveRebounds: 0,
    totalRebounds: 2,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "2",
    turnovers: 0,
  },
  {
    firstName: "Sandro",
    lastName: "Mamukelashvili",
    teamId: 21,
    playerId: 2830,
    points: 0,
    fgm: 0,
    fga: 1,
    fgp: "0.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 0,
    tpa: 0,
    tpp: "0.0",
    offensiveRebounds: 0,
    defensiveRebounds: 1,
    totalRebounds: 1,
    assists: 1,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "9",
    turnovers: 0,
  },
  {
    firstName: "Jordan",
    lastName: "Nwora",
    teamId: 21,
    playerId: 2628,
    points: 15,
    fgm: 6,
    fga: 13,
    fgp: "46.2",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 3,
    tpa: 6,
    tpp: "50.0",
    offensiveRebounds: 0,
    defensiveRebounds: 6,
    totalRebounds: 6,
    assists: 1,
    steals: 1,
    blocks: 1,
    fouls: 3,
    plusMinus: "6",
    turnovers: 1,
  },
  {
    firstName: "Justin",
    lastName: "Robinson",
    teamId: 21,
    playerId: 2207,
    points: 3,
    fgm: 1,
    fga: 2,
    fgp: "50.0",
    ftm: 0,
    fta: 0,
    ftp: "0.0",
    tpm: 1,
    tpa: 2,
    tpp: "50.0",
    offensiveRebounds: 0,
    defensiveRebounds: 0,
    totalRebounds: 0,
    assists: 0,
    steals: 0,
    blocks: 0,
    fouls: 0,
    plusMinus: "11",
    turnovers: 0,
  },
];

function Game() {
  const {gameId} = useParams();
  const [game, setGame] = React.useState<IGame | undefined>(undefined);
  const [homeTeamId, setHomeTeamId] = React.useState<number>(0);
  const [awayTeamId, setAwayTeamId] = React.useState<number>(0);
  const [homeTeamStats, setHomeTeamStats] = React.useState<
    IGameTeamStats | undefined
  >();
  const [awayTeamStats, setAwayTeamStats] = React.useState<
    IGameTeamStats | undefined
  >();
  const [playerStats, setPlayerStats] = React.useState<IPlayerStats[]>([]);

  const [comments, setComments] = React.useState<IGameComment[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      const gameResponse = await getIndividualGameByGameId(Number(gameId));
      setGame(gameResponse);
      if (gameResponse) {
        setHomeTeamId(gameResponse.homeTeamId);
        setAwayTeamId(gameResponse.awayTeamId);
        const gameStatsResponse = await getGameStatsData(Number(gameId));
        setHomeTeamStats(
          gameStatsResponse[0].teamId === gameResponse?.homeTeamId
            ? gameStatsResponse[0]
            : gameStatsResponse[1]
        );
        setAwayTeamStats(
          gameStatsResponse[0].teamId === gameResponse?.awayTeamId
            ? gameStatsResponse[0]
            : gameStatsResponse[1]
        );
        const playerStatsResponse = await getPlayerStatsPerGameData(
          Number(gameId)
        );
        setPlayerStats(playerStatsResponse);
        const commentsResponse = await getGameCommentsByGame(Number(gameId));
        setComments(commentsResponse);
      }
    };

    fetchData();
  }, [gameId]);

  return (
    <div className='page pt-5'>
      {!game && <div>Loading...</div>}
      {game && (
        <>
          <div className='d-flex'>
            <div className='me-5'>
              <LiveGameCard game={game} />
              {homeTeamStats && awayTeamStats && (
                <GameTeamStats
                  awayTeamStats={awayTeamStats}
                  homeTeamStats={homeTeamStats}
                />
              )}
            </div>

            <div className='d-flex flex-column'>
              <GameTeamPlayerStats
                stats={playerStats}
                awayTeamId={awayTeamId}
                homeTeamId={homeTeamId}
              />
              <GameComments
                comments={comments}
                gameId={Number(gameId)}
                setComments={setComments}
              />
            </div>
          </div>
        </>
      )}
    </div>
  );
}

export default Game;
